/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly 2.2.0.Final - 1.4.0.Final
 * Generated at: 2017-10-02 09:03:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.jboss.errai.security.server.FormAuthenticationScheme;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.jboss.errai.security.server.FormAuthenticationScheme");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("  <title>Drools Workbench</title>\n");
      out.write("\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("    * {\n");
      out.write("      font-family: Helvetica, Arial, sans-serif;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    body {\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("      color: #fff;\n");
      out.write("      background: url('images/bg-login.png') repeat #1b1b1b;\n");
      out.write("      font-size: 14px;\n");
      out.write("      text-shadow: #050505 0 -1px 0;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    li {\n");
      out.write("      list-style: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #dummy {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 0;\n");
      out.write("      left: 0;\n");
      out.write("      border-bottom: solid 3px #777973;\n");
      out.write("      height: 250px;\n");
      out.write("      width: 100%;\n");
      out.write("      background: url('images/bg-login-top.png') repeat #fff;\n");
      out.write("      z-index: 1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #dummy2 {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 0;\n");
      out.write("      left: 0;\n");
      out.write("      border-bottom: solid 2px #545551;\n");
      out.write("      height: 252px;\n");
      out.write("      width: 100%;\n");
      out.write("      background: transparent;\n");
      out.write("      z-index: 2;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #login-wrapper {\n");
      out.write("      margin: 0 0 0 -160px;\n");
      out.write("      width: 320px;\n");
      out.write("      text-align: center;\n");
      out.write("      z-index: 99;\n");
      out.write("      position: absolute;\n");
      out.write("      top: 0;\n");
      out.write("      left: 50%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #login-top {\n");
      out.write("      height: 120px;\n");
      out.write("      width: 401px;\n");
      out.write("      padding-top: 20px;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #login-content {\n");
      out.write("      margin-top: 120px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    label {\n");
      out.write("      width: 70px;\n");
      out.write("      float: left;\n");
      out.write("      padding: 8px;\n");
      out.write("      line-height: 14px;\n");
      out.write("      margin-top: -4px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    input.text-input {\n");
      out.write("      width: 200px;\n");
      out.write("      float: right;\n");
      out.write("      -moz-border-radius: 4px;\n");
      out.write("      -webkit-border-radius: 4px;\n");
      out.write("      border-radius: 4px;\n");
      out.write("      background: #fff;\n");
      out.write("      border: solid 1px transparent;\n");
      out.write("      color: #555;\n");
      out.write("      padding: 8px;\n");
      out.write("      font-size: 13px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    input.button {\n");
      out.write("      float: right;\n");
      out.write("      padding: 6px 10px;\n");
      out.write("      color: #fff;\n");
      out.write("      font-size: 14px;\n");
      out.write("      background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#a4d04a), to(#459300));\n");
      out.write("      text-shadow: #050505 0 -1px 0;\n");
      out.write("      background-color: #459300;\n");
      out.write("      -moz-border-radius: 4px;\n");
      out.write("      -webkit-border-radius: 4px;\n");
      out.write("      border-radius: 4px;\n");
      out.write("      border: solid 1px transparent;\n");
      out.write("      font-weight: bold;\n");
      out.write("      cursor: pointer;\n");
      out.write("      letter-spacing: 1px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    input.button:hover {\n");
      out.write("      background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#a4d04a), to(#a4d04a), color-stop(80%, #76b226));\n");
      out.write("      text-shadow: #050505 0 -1px 2px;\n");
      out.write("      background-color: #a4d04a;\n");
      out.write("      color: #fff;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    div.error {\n");
      out.write("      padding: 8px;\n");
      out.write("      background: rgb(52, 4, 0);\n");
      out.write("      -moz-border-radius: 8px;\n");
      out.write("      -webkit-border-radius: 8px;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      border: solid 1px transparent;\n");
      out.write("      margin: 6px 0;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"login\">\n");
      out.write("\n");
      out.write("<div id=\"login-wrapper\" class=\"png_bg\">\n");
      out.write("  <div id=\"login-top\">\n");
      out.write("    <img src=\"images/uf_logo.png\" alt=\"UberFire Logo\" title=\"Powered By Uberfire\"/>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div id=\"login-content\">\n");
      out.write("    <form action=\"uf_security_check\" method=\"post\">\n");
      out.write("      <p>\n");
      out.write("        <label>Username</label>\n");
      out.write("        <input value=\"\" name=\"uf_username\" class=\"text-input\" type=\"text\"/>\n");
      out.write("        <br style=\"clear: both\"/>\n");
      out.write("      </p>\n");
      out.write("\n");
      out.write("      <p>\n");
      out.write("        <label>Password</label>\n");
      out.write("        <input name=\"uf_password\" class=\"text-input\" type=\"password\"/>\n");
      out.write("        <br style=\"clear: both\"/>\n");
      out.write("      </p>\n");
      out.write("\n");
      out.write("      <p>\n");
      out.write("        ");
 if (request.getParameter("gwt.codesvr") != null) { 
      out.write("\n");
      out.write("        <input type=\"hidden\" name=\"gwt.codesvr\" value=\"");
      out.print( org.owasp.encoder.Encode.forHtmlAttribute(request.getParameter("gwt.codesvr")) );
      out.write("\"/>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (request.getParameter( FormAuthenticationScheme.LOGIN_ERROR_QUERY_PARAM ) != null) { 
      out.write("\n");
      out.write("        <span class=\"error\">Login failed. Please try again.</span>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <input class=\"button\" type=\"submit\" value=\"Sign In\"/>\n");
      out.write("      </p>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<div id=\"dummy\"></div>\n");
      out.write("<div id=\"dummy2\"></div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
